
all:

generate-4:
	gcc -fdump-ada-spec -I/home/godunko/local/llvm/include/ /home/godunko/local/llvm/include/clang-c/Index.h

generate-5:
	gcc -fdump-ada-spec -I/home/godunko/local/llvm-5.0.0/include/ /home/godunko/local/llvm-5.0.0/include/clang-c/Index.h
